### ISSUE TITLE
[Question] Failed decrypted some files

### ISSUE THREAD

**Issue by hiroshiyuri** [UlyssesWu/FreeMote#76] opened 2022-04-05 03:58 UTC
Hi there! 🙋🏻‍♂️

I decrypted the files below with FreeMote v3.1.1 and four files failed.

No error messages were displayed. 🤔
Please see screenshots:

![Screenshot_FreeMote](https://user-images.githubusercontent.com/88515571/161674245-0e71a2bc-dac7-4a57-aa36-e97149e7fecb.png)

![Screenshot_FreeMote_files](https://user-images.githubusercontent.com/88515571/161674281-6cc86cca-0420-4cd5-9d9b-28215fdc723a.png)

![Screenshot_FreeMote_file_up05_02_03](https://user-images.githubusercontent.com/88515571/161674311-5f69a534-4dba-4262-bd4b-f90b2bbe9d1c.png)

Attached are the files `scenario_body.bin` and `scenario_info.psb.m` into ZIP.

```bash
psbdecompile info-psb -k 523aad2de7132 scenario_info.psb.m
```

Can you help me? Please?

[scenario_body.zip](https://github.com/UlyssesWu/FreeMote/files/8414690/scenario_body.zip)

**Comment by UlyssesWu** [comment] 2022-04-05 05:47
Looks like a bug. I will take a look later.

**Comment by UlyssesWu** [comment] 2022-04-05 07:24
In fact it has been fixed in #69 . I haven't got ready for a new version, so you can try the latest build for now:
https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

**Comment by hiroshiyuri** [comment] 2022-04-05 19:47
> In fact it has been fixed in #69 . I haven't got ready for a new version, so you can try the latest build for now: https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts
> 
> EDIT: use https://github.com/UlyssesWu/FreeMote/releases/tag/v3.2.0

Thank you for answer!

Ok now all files decrypted! 🙂👍

But building without to edit any `*.scn.m` keeps crashing the game.

```bash
psbuild info-psb -k 523aad2de7132 scenario_info.psb.m.json
```

This scenario is from Gotoubun no Hanayome Visual Novel.

HEX and files size before -> after are diferent. I continue investigate. 👨‍💻

![scenario info before and after](https://user-images.githubusercontent.com/88515571/161836931-c8f60d52-9199-4502-9328-8f0c99e05d3a.png)

![scenario hex](https://user-images.githubusercontent.com/88515571/161836961-5e9ddb0a-35de-4969-b843-b3b17d2f9fbb.png)

**Comment by UlyssesWu** [comment] 2022-04-06 02:23
> HEX and files size before -> after are diferent
This is normal. Usually the generated file will not be 100% same as before since there could be some string sorting things and sting indexes will be different. 

You are not the first one working on this game. There are some issues before like #66 . I haven't seen any other people reporting this problem.

**Comment by UlyssesWu** [comment] 2022-04-06 06:43
I have noticed there seems to be some extra bytes after repacking. Maybe that's a bug. I will take a look later.

**Comment by UlyssesWu** [comment] 2022-04-06 08:42
Have a try with the latest build, although I think this may not be the cause
https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

**Comment by hiroshiyuri** [comment] 2022-04-06 16:38
> Have a try with the latest build, although I think this may not be the cause https://ci.appveyor.com/project/UlyssesWu/freemote/build/artifacts

It isn't the cause.

I found a external issue.

![Screenshot_Yuzu_1](https://user-images.githubusercontent.com/88515571/162023687-616380a4-4b66-4740-ba12-ce192bf56fab.png)

The game edited with FreeMote v3.2.1 crash when apply the Patch Update 1.0.2 🤦🏻‍♂️

![Screenshot_Yuzu_2](https://user-images.githubusercontent.com/88515571/162023806-ad7f50d1-8b56-4bdf-92c4-51f3b6427c24.png)

Unchecking the add-on...
It's work and with extra characters and symbols! Incredible! 🙌

![Screenshot_Yuzu_3](https://user-images.githubusercontent.com/88515571/162023905-6ec35f66-cadc-4a29-88a2-f7cfa0b5f760.png)

Thanks very much! 👍

**Comment by UlyssesWu** [comment] 2022-04-06 17:11
Okay nice.
If you figured out what's wrong with 1.0.2 update one day and it turned out to be a bug of FreeMote, you can submit a new issue.

Good luck!

**Closed by UlyssesWu** 2022-04-06 17:11 UTC
Labels: bug, psb.m
