### ISSUE TITLE
[viewer]when I drag .psb into FreeMoteViewer.exe, nothing happen

### ISSUE THREAD

**Issue by killeromg007** [UlyssesWu/FreeMote#137] opened 2024-10-07 13:41 UTC
Platfrom : PC/Win10
Psb: https://drive.google.com/file/d/19p6EUCj4ulX0cpD3PhL_9Qca7P4gbu8X/view?usp=sharing
Issue: https://drive.google.com/file/d/1xSBqiGoBoSXq7sjiTzaxpqizUfbDdUM9/view?usp=sharing

**Comment by killeromg007** [comment] 2024-10-07 13:43
@UlyssesWu

**Comment by UlyssesWu** [comment] 2024-10-07 13:48
duplicate of #136

**Closed by UlyssesWu** 2024-10-07 13:48 UTC
