### ISSUE TITLE
The Quintessential Quintuplets ∬: Summer Memories

### ISSUE THREAD

**Issue by MarquesCoding** [UlyssesWu/FreeMote#62] opened 2021-06-27 00:00 UTC
Hey. I encountered one problem when trying to unpack scenario_info.psb.m and scenario_body.bin using Freemote. I'm trying to translate the game and have tried many methods. I've extracted the switch game using Yuzu and it's given me a load of _info.psb.m & _body.bin files and I presume they are encrypted using MD5 or something, I presume I need a key to decrypt this... Was wondering how do I obtain a key or is there a way of brute force my way in?

Thanks

**Comment by lsssk11331** [comment] 2021-06-27 00:35
the key for this game was already shared on zenhax forum, you can search for it.

**Comment by UlyssesWu** [comment] 2021-06-27 05:08
duplicate of https://zenhax.com/viewtopic.php?t=15051

**Comment by UlyssesWu** [comment] 2021-07-04 07:39
Close due to no response.

**Closed by UlyssesWu** 2021-07-04 07:39 UTC
Labels: duplicate, question

**Comment by PantsuMeow** [comment] 2023-06-16 15:35
This webpage is 404. Can you resend the key? I really need it,Thank you very much！:)

**Comment by UlyssesWu** [comment] 2023-06-16 15:57
> This webpage is 404. Can you resend the key? I really need it,Thank you very much！:)

You can view the saved page via web.archive.org . It is 523aad2de7132
